import express from 'express';
import dotenv from 'dotenv';
import cors from 'cors';
import { sequelize } from './config/database';
import { authRouter } from './routes/auth.routes';
import { adminRouter } from './routes/admin.routes';
import { storeRouter } from './routes/store.routes';
import { swaggerUiServe, swaggerUiSetup } from './swagger/swagger';
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/auth', authRouter);
app.use('/api/admin', adminRouter);
app.use('/api/stores', storeRouter);
app.use('/api-docs', swaggerUiServe, swaggerUiSetup);
const port = process.env.PORT || 4000;
sequelize.authenticate().then(()=>console.log('DB connected')).catch(e=>console.error(e));
app.listen(port, ()=>console.log('Listening on', port));
